version: '3.8'
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

  api:
    build: .
    ports:
      - '4000:4000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/fs-db
      - NODE_ENV=production
    depends_on:
      - mongo

volumes:
  mongo-data:
